### ISSUE TITLE
Release 1.3 ?

### ISSUE THREAD

**Issue by Lcfvs** [php-fig/http-message-util#11]
Hi,

Thanks for the merge... but don't forget to release it, please. ;)

**Comment by Jean85** [comment]
@weierophinney can you do it? I think you have the tooling ready to do it automatically...

Otherwise ping me.

BTW should it be 1.1.3?

**Comment by weierophinney** [comment]
Done: https://github.com/php-fig/http-message-util/releases/tag/1.1.3

**Comment by Lcfvs** [comment]
Thx
